INSERT INTO permisos_definidos (codigo, modulo, accion, descripcion, es_sensible) VALUES
  ('tenants.crear',                   'tenants',      'crear',                  'Crear nuevos tenants',                        true),
  ('tenants.suspender',               'tenants',      'suspender',              'Suspender un tenant',                         true),
  ('clientes.ver',                    'clientes',     'ver',                    'Ver lista de clientes',                       false),
  ('clientes.crear',                  'clientes',     'crear',                  'Crear cliente',                               false),
  ('clientes.editar',                 'clientes',     'editar',                 'Editar cliente existente',                    false),
  ('clientes.eliminar',               'clientes',     'eliminar',               'Eliminar cliente',                            true),
  ('clientes.exportar',               'clientes',     'exportar',               'Exportar lista a Excel',                      false),
  ('productos.ver',                   'productos',    'ver',                    'Ver catálogo',                                false),
  ('productos.crear',                 'productos',    'crear',                  'Crear producto',                              false),
  ('productos.editar',                'productos',    'editar',                 'Editar producto',                             false),
  ('productos.eliminar',              'productos',    'eliminar',               'Eliminar producto',                           true),
  ('productos.ver_costo',             'productos',    'ver_costo',              'Ver precio de compra (costo)',                 true),
  ('productos.editar_margen',         'productos',    'editar_margen',          'Cambiar margen mínimo',                       true),
  ('productos.importar',              'productos',    'importar',               'Importar masivamente desde Excel',            false),
  ('cotizaciones.ver',                'cotizaciones', 'ver',                    'Ver cotizaciones',                            false),
  ('cotizaciones.crear',              'cotizaciones', 'crear',                  'Crear cotización',                            false),
  ('cotizaciones.editar',             'cotizaciones', 'editar',                 'Editar cotización borrador',                  false),
  ('cotizaciones.aprobar',            'cotizaciones', 'aprobar',                'Aprobar cotización',                          false),
  ('cotizaciones.eliminar',           'cotizaciones', 'eliminar',               'Eliminar cotización',                         true),
  ('cotizaciones.cambiar_margen',     'cotizaciones', 'cambiar_margen',         'Modificar margen en línea',                   false),
  ('cotizaciones.descuento_excepcional', 'cotizaciones', 'descuento_excepcional', 'Aplicar descuento mayor al estándar',      true),
  ('ordenes.ver',                     'ordenes',      'ver',                    'Ver órdenes de compra',                       false),
  ('ordenes.crear',                   'ordenes',      'crear',                  'Crear orden de compra',                       false),
  ('ordenes.aprobar',                 'ordenes',      'aprobar',                'Aprobar orden',                               false),
  ('inventario.ver',                  'inventario',   'ver',                    'Ver kardex',                                  false),
  ('inventario.ajuste_manual',        'inventario',   'ajuste_manual',          'Ajustar stock manualmente',                   true),
  ('guias.ver',                       'guias',        'ver',                    'Ver guías',                                   false),
  ('guias.crear',                     'guias',        'crear',                  'Crear guía de remisión',                      false),
  ('guias.anular',                    'guias',        'anular',                 'Anular guía',                                 true),
  ('facturas.ver',                    'facturas',     'ver',                    'Ver facturas',                                false),
  ('facturas.emitir',                 'facturas',     'emitir',                 'Emitir factura/boleta',                       false),
  ('facturas.anular',                 'facturas',     'anular',                 'Anular factura (NC)',                         true),
  ('facturas.reenviar_sunat',         'facturas',     'reenviar_sunat',         'Forzar reenvío a SUNAT',                      true),
  ('credito.ver',                     'credito',      'ver',                    'Ver cuentas por cobrar',                      false),
  ('credito.otorgar',                 'credito',      'otorgar',                'Otorgar/modificar línea de crédito',          true),
  ('credito.registrar_pago',          'credito',      'registrar_pago',         'Registrar pago de cliente',                   false),
  ('reportes.ver',                    'reportes',     'ver',                    'Ver dashboard y reportes',                    false),
  ('reportes.exportar',               'reportes',     'exportar',               'Exportar reportes a Excel',                   false),
  ('admin.usuarios.ver',              'admin',        'usuarios.ver',           'Ver usuarios del tenant',                     false),
  ('admin.usuarios.invitar',          'admin',        'usuarios.invitar',       'Invitar nuevos usuarios',                     true),
  ('admin.usuarios.suspender',        'admin',        'usuarios.suspender',     'Suspender usuarios',                          true),
  ('admin.roles.ver',                 'admin',        'roles.ver',              'Ver roles y permisos',                        false),
  ('admin.roles.editar',              'admin',        'roles.editar',           'Crear/editar roles y permisos',               true),
  ('admin.config.editar',             'admin',        'config.editar',          'Editar configuración del tenant',             true)
ON CONFLICT (codigo) DO UPDATE SET
  modulo      = EXCLUDED.modulo,
  accion      = EXCLUDED.accion,
  descripcion = EXCLUDED.descripcion,
  es_sensible = EXCLUDED.es_sensible;
